[2024-12-30T16:59:00.538+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T16:59:00.549+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_clickhouse_connection.test_clickhouse_connection_task manual__2024-12-30T16:53:50.263279+00:00 [queued]>
[2024-12-30T16:59:00.554+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_clickhouse_connection.test_clickhouse_connection_task manual__2024-12-30T16:53:50.263279+00:00 [queued]>
[2024-12-30T16:59:00.554+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-30T16:59:00.563+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): test_clickhouse_connection_task> on 2024-12-30 16:53:50.263279+00:00
[2024-12-30T16:59:00.567+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T16:59:00.568+0000] {standard_task_runner.py:72} INFO - Started process 175 to run task
[2024-12-30T16:59:00.569+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_clickhouse_connection', 'test_clickhouse_connection_task', 'manual__2024-12-30T16:53:50.263279+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/click-test.py', '--cfg-path', '/tmp/tmpq0dn1jeh']
[2024-12-30T16:59:00.570+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask test_clickhouse_connection_task
[2024-12-30T16:59:00.601+0000] {task_command.py:467} INFO - Running <TaskInstance: test_clickhouse_connection.test_clickhouse_connection_task manual__2024-12-30T16:53:50.263279+00:00 [running]> on host 2d81759ef064
[2024-12-30T16:59:00.650+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_clickhouse_connection' AIRFLOW_CTX_TASK_ID='test_clickhouse_connection_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T16:53:50.263279+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T16:53:50.263279+00:00'
[2024-12-30T16:59:00.650+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T16:59:08.661+0000] {connection.py:411} WARNING - Failed to connect to clickhouse:8123
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 329, in _init_connection
    self.socket = self._create_socket(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 280, in _create_socket
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
[2024-12-30T16:59:08.662+0000] {logging_mixin.py:190} INFO - Failed to connect to ClickHouse: Code: 210. Temporary failure in name resolution (clickhouse:8123)
[2024-12-30T16:59:08.662+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/click-test.py", line 22, in test_clickhouse_connection
    result = client.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 420, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Temporary failure in name resolution (clickhouse:8123)
[2024-12-30T16:59:08.669+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_clickhouse_connection, task_id=test_clickhouse_connection_task, run_id=manual__2024-12-30T16:53:50.263279+00:00, execution_date=20241230T165350, start_date=20241230T165900, end_date=20241230T165908
[2024-12-30T16:59:08.680+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T16:59:08.680+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task test_clickhouse_connection_task (Code: 210. Temporary failure in name resolution (clickhouse:8123); 175)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/click-test.py", line 22, in test_clickhouse_connection
    result = client.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/clickhouse_driver/connection.py", line 420, in connect
    raise err
clickhouse_driver.errors.NetworkError: Code: 210. Temporary failure in name resolution (clickhouse:8123)
[2024-12-30T16:59:08.715+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-30T16:59:08.725+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T16:59:08.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
